import { quoteDynamicValue } from './dynamic.ts'

/**
 * A hostname alias is a nickname, never a rename.
 *
 * Docker cannot rewrite a label on a running container, and driving Compose
 * from the panel is out (ADR 0001), so an alias can only ever *add* a router
 * beside the project's own. Both hostnames answer, which is the correct
 * behaviour and is documented as such rather than filed as a bug.
 */
export interface StoredAlias {
  /** Compose project the alias belongs to; kept so a whole project can be dropped. */
  project: string
  /** Compose service, for display and for removing one alias. */
  service: string
  /** Container name, never the Compose service alias: two projects can both have `web`. */
  container: string
  host: string
  port: number
  entryPoint: string
}

export const ALIASES_MARKER = '# portta-aliases: '

const HEADER = [
  '# ============================================================================',
  '# Generated by Portta panel. Edits are overwritten.',
  '# ============================================================================',
  '# Hostname aliases: one additional router per aliased service. The project\'s',
  "# own router is never touched, so both hostnames answer. See docs/product/guides/web-ui.md.",
  '# ============================================================================',
]

export function aliasRouterName(project: string, service: string): string {
  return `portta-alias-${project}-${service}`.replace(/[^a-zA-Z0-9-]/g, '-')
}

/** The canonical Traefik file renderer, used by both the panel and the CLI. */
export function renderAliases(aliases: StoredAlias[]): string {
  const lines = [...HEADER, `${ALIASES_MARKER}${JSON.stringify(aliases)}`, '']
  if (aliases.length === 0) {
    lines.push('# No alias is set. A project is reached on the hostname it derives.')
    return `${lines.join('\n')}\n`
  }

  lines.push('http:', '  routers:')
  for (const alias of aliases) {
    const router = aliasRouterName(alias.project, alias.service)
    lines.push(`    ${router}:`)
    lines.push(`      rule: ${quoteDynamicValue(`Host(\`${alias.host}\`)`)}`)
    lines.push(`      entryPoints: [${alias.entryPoint}]`)
    lines.push(`      service: ${router}`)
  }

  lines.push('  services:')
  for (const alias of aliases) {
    const router = aliasRouterName(alias.project, alias.service)
    lines.push(`    ${router}:`, '      loadBalancer:', '        servers:')
    lines.push(`          - url: ${quoteDynamicValue(`http://${alias.container}:${alias.port}`)}`)
  }

  lines.push('')
  return lines.join('\n')
}

/** Reads the state back out of the file the panel itself wrote. */
export function parseAliases(contents: string | null): StoredAlias[] {
  if (!contents) return []
  const line = contents.split('\n').find((entry) => entry.startsWith(ALIASES_MARKER))
  if (!line) return []
  try {
    const parsed = JSON.parse(line.slice(ALIASES_MARKER.length)) as unknown
    if (!Array.isArray(parsed)) return []
    return parsed.filter((entry): entry is StoredAlias => {
      const value = entry as Record<string, unknown>
      return typeof value?.host === 'string' && typeof value?.container === 'string'
    })
  } catch {
    return []
  }
}
