export const PANEL_AUTH_MIDDLEWARE = 'portta-web-auth'
export const FORWARD_AUTH_MIDDLEWARE = 'portta-forward-auth'
export const AUTH_SERVICE = 'portta-auth'
export const AUTH_PATH_PREFIX = '/__portta/auth'

import type { ProtectionStore } from './protections.ts'

const PANEL_HEADER = [
  '# ============================================================================',
  '# Generated by Portta panel. Edits are overwritten.',
  '# ============================================================================',
  '# The panel writes this file and one other in this directory, and nothing',
  '# else here. See docs/adr/0011-panel-reads-traefik-writes-one-file.md.',
  '# ============================================================================',
  '',
]

export class UnsafeDynamicValueError extends Error {}

export function quoteDynamicValue(value: string): string {
  if (/["\\\n\r]/.test(value)) throw new UnsafeDynamicValueError(`refusing to write a value containing quotes or newlines: ${value}`)
  return `"${value}"`
}

function dynamicName(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'protection'
}

function ruleHost(authority: string): string {
  try { return new URL(`http://${authority}`).hostname } catch { return authority }
}

/** The shared ForwardAuth service, middleware and unprotected login routers. */
export function renderAuthDynamic(store: ProtectionStore): string {
  const lines = [
    '# ============================================================================',
    '# Generated by Portta. Edits are overwritten.',
    '# ============================================================================',
    '# ForwardAuth is a separate process. The reserved login routers below must',
    '# never reference either authentication middleware. See ADR 0027.',
    '# ============================================================================',
    'http:',
    '  routers:',
  ]
  for (const protection of store.protections) {
    const name = `portta-auth-login-${dynamicName(protection.scope)}`
    lines.push(`    ${name}:`)
    lines.push(`      rule: ${quoteDynamicValue(`Host(\`${ruleHost(protection.host)}\`) && PathPrefix(\`${AUTH_PATH_PREFIX}\`)`)}`)
    lines.push(`      entryPoints: [${protection.entryPoints.join(', ')}]`)
    lines.push('      priority: 10000')
    lines.push(`      service: ${AUTH_SERVICE}`)
  }
  lines.push(
    '  services:',
    `    ${AUTH_SERVICE}:`,
    '      loadBalancer:',
    '        servers:',
    `          - url: ${quoteDynamicValue('http://portta-auth:4180')}`,
    '  middlewares:',
    `    ${FORWARD_AUTH_MIDDLEWARE}:`,
    '      forwardAuth:',
    `        address: ${quoteDynamicValue('http://portta-auth:4180/verify')}`,
    '        trustForwardHeader: true',
    '        authResponseHeaders: [X-Forwarded-User]',
    `    ${PANEL_AUTH_MIDDLEWARE}:`,
    '      forwardAuth:',
    `        address: ${quoteDynamicValue('http://portta-auth:4180/verify?scope=panel')}`,
    '        trustForwardHeader: true',
    '        authResponseHeaders: [X-Forwarded-User]',
    '',
  )
  return lines.join('\n')
}

/** The canonical panel BasicAuth middleware renderer used by both surfaces. */
export function renderPanelAuth(options: { user: string; hash: string } | null): string {
  if (!options) {
    return [
      ...PANEL_HEADER,
      '# PORTTA_WEB_AUTH is not `basic`, so the panel declares no middleware.',
      '# A router that references one will be rejected by Traefik, which is the',
      '# correct direction to fail.',
    ].join('\n') + '\n'
  }
  return [
    ...PANEL_HEADER,
    '# BasicAuth in front of the panel\'s own router. There is no session, no',
    '# cookie and no login form: the request either reaches the container or it',
    '# does not. See docs/adr/0012-panel-authentication-is-traefiks.md.',
    'http:',
    '  middlewares:',
    `    ${PANEL_AUTH_MIDDLEWARE}:`,
    '      basicAuth:',
    '        users:',
    `          - ${quoteDynamicValue(`${options.user}:${options.hash}`)}`,
    '        realm: "Portta"',
    '        removeHeader: true',
    '',
  ].join('\n')
}
