export const PANEL_AUTH_MIDDLEWARE = 'dev-gateway-web-auth'

const PANEL_HEADER = [
  '# ============================================================================',
  '# Generated by the Dev Gateway panel. Edits are overwritten.',
  '# ============================================================================',
  '# The panel writes this file and one other in this directory, and nothing',
  '# else here. See docs/adr/0011-panel-reads-traefik-writes-one-file.md.',
  '# ============================================================================',
  '',
]

export class UnsafeDynamicValueError extends Error {}

export function quoteDynamicValue(value: string): string {
  if (/["\\\n\r]/.test(value)) throw new UnsafeDynamicValueError(`refusing to write a value containing quotes or newlines: ${value}`)
  return `"${value}"`
}

/** The canonical panel BasicAuth middleware renderer used by both surfaces. */
export function renderPanelAuth(options: { user: string; hash: string } | null): string {
  if (!options) {
    return [
      ...PANEL_HEADER,
      '# DEV_GATEWAY_WEB_AUTH is not `basic`, so the panel declares no middleware.',
      '# A router that references one will be rejected by Traefik, which is the',
      '# correct direction to fail.',
    ].join('\n') + '\n'
  }
  return [
    ...PANEL_HEADER,
    '# BasicAuth in front of the panel\'s own router. There is no session, no',
    '# cookie and no login form: the request either reaches the container or it',
    '# does not. See docs/adr/0012-panel-authentication-is-traefiks.md.',
    'http:',
    '  middlewares:',
    `    ${PANEL_AUTH_MIDDLEWARE}:`,
    '      basicAuth:',
    '        users:',
    `          - ${quoteDynamicValue(`${options.user}:${options.hash}`)}`,
    '        realm: "Dev Gateway"',
    '        removeHeader: true',
    '',
  ].join('\n')
}
