import { FORWARD_AUTH_MIDDLEWARE, quoteDynamicValue } from './dynamic.ts'

export type SharedRouteMode = 'public' | 'protected'

export interface StoredSharedRoute {
  id: string
  host: string
  entryPoint: string
  container: string
  port: number
  mode: SharedRouteMode
  user?: string | null
  hash?: string | null
}

export const SHARES_MARKER = '# portta-shares: '

const HEADER = [
  '# ============================================================================',
  '# Generated by Portta panel. Edits are overwritten.',
  '# ============================================================================',
  '# Temporary shares: one additional hostname per service, each with an expiry.',
  '# A project\'s own router is never touched, and revoking a share deletes a',
  '# block from this file. See docs/product/guides/sharing.md.',
  '# ============================================================================',
]

export function shareRouterName(id: string): string {
  return `portta-share-${id}`
}

/** The canonical Traefik file renderer used by both the panel and the CLI. */
export function renderShares<T extends StoredSharedRoute>(shares: T[]): string {
  // The marker remains the durable share catalogue, but credentials belong
  // only in the private protection store. Strip legacy hashes on every write.
  const catalogue = shares.map(({ hash: _hash, ...share }) => share)
  const lines = [...HEADER, `${SHARES_MARKER}${JSON.stringify(catalogue)}`, '']
  if (shares.length === 0) {
    lines.push('# Nothing is shared. "Private" is the absence of a share, not a deny rule.')
    return `${lines.join('\n')}\n`
  }

  lines.push('http:', '  routers:')
  for (const share of shares) {
    const router = shareRouterName(share.id)
    lines.push(`    ${router}:`)
    lines.push(`      rule: ${quoteDynamicValue(`Host(\`${share.host}\`)`)}`)
    lines.push(`      entryPoints: [${share.entryPoint}]`)
    if (share.mode === 'protected') lines.push(`      middlewares: [${FORWARD_AUTH_MIDDLEWARE}]`)
    lines.push(`      service: ${router}`)
  }

  lines.push('  services:')
  for (const share of shares) {
    const router = shareRouterName(share.id)
    lines.push(`    ${router}:`, '      loadBalancer:', '        servers:')
    lines.push(`          - url: ${quoteDynamicValue(`http://${share.container}:${share.port}`)}`)
  }

  lines.push('')
  return lines.join('\n')
}
