import { quoteDynamicValue } from './dynamic.ts'

export type SharedRouteMode = 'public' | 'protected'

export interface StoredSharedRoute {
  id: string
  host: string
  entryPoint: string
  container: string
  port: number
  mode: SharedRouteMode
  user?: string | null
  hash?: string | null
}

export const SHARES_MARKER = '# portta-shares: '

const HEADER = [
  '# ============================================================================',
  '# Generated by Portta panel. Edits are overwritten.',
  '# ============================================================================',
  '# Temporary shares: one additional hostname per service, each with an expiry.',
  '# A project\'s own router is never touched, and revoking a share deletes a',
  '# block from this file. See docs/sharing.md.',
  '# ============================================================================',
]

export function shareRouterName(id: string): string {
  return `portta-share-${id}`
}

/** The canonical Traefik file renderer used by both the panel and the CLI. */
export function renderShares<T extends StoredSharedRoute>(shares: T[]): string {
  const lines = [...HEADER, `${SHARES_MARKER}${JSON.stringify(shares)}`, '']
  if (shares.length === 0) {
    lines.push('# Nothing is shared. "Private" is the absence of a share, not a deny rule.')
    return `${lines.join('\n')}\n`
  }

  lines.push('http:', '  routers:')
  for (const share of shares) {
    const router = shareRouterName(share.id)
    lines.push(`    ${router}:`)
    lines.push(`      rule: ${quoteDynamicValue(`Host(\`${share.host}\`)`)}`)
    lines.push(`      entryPoints: [${share.entryPoint}]`)
    if (share.mode === 'protected') lines.push(`      middlewares: [${router}-auth]`)
    lines.push(`      service: ${router}`)
  }

  lines.push('  services:')
  for (const share of shares) {
    const router = shareRouterName(share.id)
    lines.push(`    ${router}:`, '      loadBalancer:', '        servers:')
    lines.push(`          - url: ${quoteDynamicValue(`http://${share.container}:${share.port}`)}`)
  }

  const protectedShares = shares.filter((share) => share.mode === 'protected')
  if (protectedShares.length > 0) {
    lines.push('  middlewares:')
    for (const share of protectedShares) {
      if (!share.user || !share.hash) throw new Error(`protected share ${share.id} has no credentials`)
      lines.push(`    ${shareRouterName(share.id)}-auth:`, '      basicAuth:', '        users:')
      lines.push(`          - ${quoteDynamicValue(`${share.user}:${share.hash}`)}`, '        removeHeader: true')
    }
  }

  lines.push('')
  return lines.join('\n')
}
