/**
 * The Cloudflare Tunnel connector's configuration.
 *
 * The shape of this file is the whole argument for the feature, so it is worth
 * stating plainly: it contains **one ingress rule for the whole gateway**.
 *
 *     ingress:
 *       - hostname: "*.portta.app"
 *         service: http://traefik:80
 *       - service: http_status:404
 *
 * Everything dynamic happens below that line, inside Traefik, which already
 * routes by Host and already learns about containers from Docker labels. So
 * publishing a new project adds a container and nothing else: no Cloudflare API
 * call, no DNS record, no connector restart, no edit to this file.
 *
 * That was measured, not assumed. On a real host:
 *
 *   - `cloudflared tunnel ingress rule` matches `web--demo.portta.app` and
 *     `api--demo--pr-42.portta.app` against the single `*.portta.app` rule, and
 *     falls through to the catch-all for the apex and for other zones.
 *   - through a live tunnel, the origin container received
 *     `Host: <the original hostname>` unchanged, which is what lets Traefik
 *     route behind the connector at all.
 *   - adding a Traefik router made a hostname start working with no change on
 *     the Cloudflare side; removing it made it stop.
 *
 * See docs/adr/0025-cloudflare-tunnel.md for the comparison against publishing
 * a port, and docs/cloudflare-tunnel.md for the operator's guide.
 */

export interface TunnelConfig {
  /** The tunnel's UUID, from `cloudflared tunnel create`. */
  id: string
  /** The zone whose wildcard is routed here, e.g. `portta.app`. */
  zone: string
  /** Where the connector reaches Traefik. A container name on the shared network. */
  origin: string
  /** Path to the credentials file *inside the connector*, never on the host. */
  credentialsFile: string
  /**
   * Hostnames that must reach something other than Traefik, in order, before
   * the wildcard. The panel's own front door is the only usual case.
   */
  extraRoutes?: Array<{ hostname: string; service: string }>
  /** Serve the apex too. Off by default: `*.zone` does not match `zone`. */
  includeApex?: boolean
}

/** cloudflared reads YAML; these are the characters that would break a scalar. */
function yamlString(value: string): string {
  if (/["\\\n\r]/.test(value)) throw new Error(`refusing to write a value containing quotes or newlines: ${value}`)
  return `"${value}"`
}

const HOSTNAME = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/i

export function isHostname(value: string): boolean {
  return HOSTNAME.test(value)
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/**
 * Render the connector's `config.yml`.
 *
 * Refuses rather than writes a file that would not work: a malformed zone
 * becomes a wildcard matching nothing, and a connector that starts and routes
 * nothing is harder to diagnose than one that refuses to start.
 */
export function renderTunnelConfig(config: TunnelConfig): string {
  if (!UUID.test(config.id)) throw new Error(`tunnel id is not a UUID: ${config.id}`)
  if (!isHostname(config.zone)) throw new Error(`tunnel zone is not a hostname: ${config.zone}`)

  const lines = [
    '# ============================================================================',
    '# Generated by Portta. Edits are overwritten.',
    '# ============================================================================',
    '# One rule for the whole gateway: every hostname under the zone reaches',
    '# Traefik, which routes it by Host to the right container. Publishing a',
    '# project therefore needs no change here and none at Cloudflare.',
    '#',
    '# See docs/adr/0025-cloudflare-tunnel.md.',
    '# ============================================================================',
    `tunnel: ${yamlString(config.id)}`,
    `credentials-file: ${yamlString(config.credentialsFile)}`,
    '',
    '# Retain the original Host header: it is the only thing Traefik routes on.',
    '# cloudflared passes it through by default, and `httpHostHeader` would',
    '# override it — which is why it is deliberately absent.',
    'ingress:',
  ]

  for (const route of config.extraRoutes ?? []) {
    if (!isHostname(route.hostname)) throw new Error(`route hostname is not a hostname: ${route.hostname}`)
    lines.push(`  - hostname: ${yamlString(route.hostname)}`, `    service: ${yamlString(route.service)}`)
  }

  if (config.includeApex) {
    // `*.example.com` does not match `example.com`; verified with
    // `cloudflared tunnel ingress rule`, which falls through to the catch-all.
    lines.push(`  - hostname: ${yamlString(config.zone)}`, `    service: ${yamlString(config.origin)}`)
  }

  lines.push(
    `  - hostname: ${yamlString(`*.${config.zone}`)}`,
    `    service: ${yamlString(config.origin)}`,
    '',
    '  # Required: a configuration with ingress rules must end in a catch-all.',
    '  # 404 rather than a proxy, so a hostname nobody configured says so',
    '  # instead of reaching whichever service answered first.',
    '  - service: http_status:404',
    '',
  )
  return lines.join('\n')
}

/** The routes a tunnel serves, for display. Never the credentials. */
export function describeTunnel(config: TunnelConfig): string[] {
  const routes = (config.extraRoutes ?? []).map((route) => `${route.hostname} -> ${route.service}`)
  if (config.includeApex) routes.push(`${config.zone} -> ${config.origin}`)
  routes.push(`*.${config.zone} -> ${config.origin}`)
  return routes
}

/**
 * The DNS record that has to exist for the zone, once.
 *
 * A wildcard CNAME to the tunnel's own subdomain. Cloudflare proxies wildcard
 * records on every plan, and `<uuid>.cfargotunnel.com` only accepts records
 * from the account that owns the tunnel, so the UUID is not a secret.
 */
export function tunnelDnsTarget(id: string): string {
  if (!UUID.test(id)) throw new Error(`tunnel id is not a UUID: ${id}`)
  return `${id}.cfargotunnel.com`
}

// ============================================================================
// The token, and why it is the only thing we ask for
// ============================================================================
// Cloudflare's dashboard hands out one copy-pasteable string per tunnel, and
// that string already contains everything a connector needs:
//
//     base64({"a": "<account tag>", "t": "<tunnel uuid>", "s": "<secret>"})
//
// which is field-for-field the credentials file a locally-managed tunnel reads:
//
//     {"AccountTag": …, "TunnelID": …, "TunnelSecret": …}
//
// Verified against cloudflared 2026.7.3: given a credentials file built this
// way, it loads it, resolves the tunnel and reaches "Registering tunnel
// connection" — failing only on the fake secret used for the test.
//
// So Portta asks for the token, the one thing that is easy to copy, and still
// runs the tunnel **locally managed**. That matters: local management is what
// lets Portta write the single wildcard ingress rule it needs. Ingress
// configured in the dashboard would put Cloudflare in charge of routing, which
// is precisely the responsibility ADR 0025 keeps with Traefik.
//
// See docs/cloudflare-tunnel.md.

export interface TunnelCredentials {
  AccountTag: string
  TunnelID: string
  TunnelSecret: string
}

export class InvalidTunnelTokenError extends Error {}

const BASE64 = /^[A-Za-z0-9+/=_-]+$/

/**
 * Decode a dashboard tunnel token into connector credentials.
 *
 * Throws rather than returning null: every caller has a person in front of it
 * who pasted something, and "that is not a tunnel token" is the useful answer.
 * The message never quotes the value, because the value is a credential.
 */
export function parseTunnelToken(token: string): TunnelCredentials {
  const trimmed = token.trim()
  if (!trimmed) throw new InvalidTunnelTokenError('no token was given')
  if (!BASE64.test(trimmed)) {
    throw new InvalidTunnelTokenError('that does not look like a tunnel token: it should be one long base64 string, usually starting with eyJ')
  }

  let decoded: string
  try {
    decoded = Buffer.from(trimmed, 'base64').toString('utf8')
  } catch {
    throw new InvalidTunnelTokenError('the token is not valid base64')
  }

  let parsed: unknown
  try {
    parsed = JSON.parse(decoded)
  } catch {
    throw new InvalidTunnelTokenError('the token did not decode to a tunnel token; copy the whole eyJ… string, not the install command around it')
  }

  const value = parsed as Record<string, unknown>
  const accountTag = typeof value?.a === 'string' ? value.a : ''
  const tunnelId = typeof value?.t === 'string' ? value.t : ''
  const secret = typeof value?.s === 'string' ? value.s : ''
  if (!accountTag || !tunnelId || !secret) {
    throw new InvalidTunnelTokenError('the token is missing the account, tunnel or secret field')
  }
  if (!UUID.test(tunnelId)) throw new InvalidTunnelTokenError('the tunnel id inside the token is not a UUID')

  return { AccountTag: accountTag, TunnelID: tunnelId, TunnelSecret: secret }
}

/** The credentials file the connector reads. Written 0600, never logged. */
export function renderTunnelCredentials(credentials: TunnelCredentials): string {
  return `${JSON.stringify(credentials)}\n`
}

/**
 * What may be shown about a token, which is almost nothing.
 *
 * The panel says "configured" and offers to replace it; it never displays the
 * value again, and this exists so a log line or a diagnostic can refer to
 * *which* token without leaking it.
 */
export function maskToken(token: string): string {
  const trimmed = token.trim()
  if (trimmed.length <= 8) return '••••'
  return `${trimmed.slice(0, 4)}…${trimmed.slice(-4)}`
}

/**
 * The tunnel's state, as the panel reports it.
 *
 * Distinguishing these is the whole value of the status card: "not working"
 * sends somebody to the wrong place, while "the token was rejected" and "the
 * connector cannot reach the edge" have completely different fixes.
 */
export const TUNNEL_STATES = [
  'not-configured',
  'configured',
  'starting',
  'connected',
  'disconnected',
  'auth-error',
  'config-error',
] as const
export type TunnelState = (typeof TUNNEL_STATES)[number]

export interface TunnelStatusInput {
  tokenConfigured: boolean
  zoneConfigured: boolean
  enabled: boolean
  containerState: string | null
  containerHealth: string | null
  /** Recent connector output, read from the container. Never persisted. */
  logTail: string
}

export interface TunnelStatus {
  state: TunnelState
  detail: string
  hint: string | null
}

const AUTH_FAILURE = /(Unauthorized|failed to authenticate|invalid tunnel secret|token is invalid|401)/i
const CONFIG_FAILURE = /(Couldn't start tunnel|validation failed|error parsing YAML|unable to parse config)/i
const REGISTERED = /Registered tunnel connection/i

/**
 * Read the connector's state from what can be observed locally.
 *
 * Deliberately derived from the container and its own logs rather than from
 * Cloudflare's API: that answer needs no credential beyond the one already
 * here, works when the account is unreachable, and describes *this* host
 * rather than the account's view of it.
 */
export function tunnelStatusFrom(input: TunnelStatusInput): TunnelStatus {
  if (!input.tokenConfigured || !input.zoneConfigured) {
    return {
      state: 'not-configured',
      detail: !input.tokenConfigured ? 'no tunnel token has been set' : 'no domain has been set',
      hint: 'Settings -> Cloudflare Tunnel',
    }
  }
  if (!input.enabled) {
    return { state: 'configured', detail: 'set up, and not enabled', hint: 'enable it to start the connector' }
  }

  // A credential the edge rejects is checked before liveness: the container is
  // running perfectly and the tunnel will never come up.
  if (AUTH_FAILURE.test(input.logTail)) {
    return {
      state: 'auth-error',
      detail: 'Cloudflare rejected the tunnel token',
      hint: 'the tunnel may have been deleted, or the token belongs to another account. Replace the token.',
    }
  }
  if (CONFIG_FAILURE.test(input.logTail)) {
    return { state: 'config-error', detail: 'the connector refused its configuration', hint: 'portta tunnel status --logs' }
  }

  if (input.containerState !== 'running') {
    return {
      state: 'disconnected',
      detail: input.containerState ? `the connector container is ${input.containerState}` : 'the connector container does not exist',
      hint: 'portta up',
    }
  }
  if (REGISTERED.test(input.logTail)) {
    return { state: 'connected', detail: 'holding registered connections to the Cloudflare edge', hint: null }
  }
  if (input.containerHealth === 'starting' || !input.logTail) {
    return { state: 'starting', detail: 'the connector is establishing its connections', hint: null }
  }
  return {
    state: 'disconnected',
    detail: 'the connector is running but has registered no connection',
    hint: 'check outbound network access; the connector dials Cloudflare on 7844/udp and 443/tcp',
  }
}

/** Whether this state should stop a service being offered a tunnel endpoint. */
export function tunnelIsUsable(state: TunnelState): boolean {
  return state === 'connected'
}
