import { mkdtempSync, readFileSync, readdirSync, writeFileSync, statSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  DynamicWriteRefused,
  GENERATED_FILES,
  PANEL_AUTH_MIDDLEWARE,
  reconcilePanelAuth,
  removeGenerated,
  renderPanelAuth,
  writeGenerated,
} from '../../src/server/core/dynamic.ts'

function scratch(): string {
  return mkdtempSync(join(tmpdir(), 'portta-dynamic-'))
}

describe('the write allowlist', () => {
  it('writes the two files it owns', () => {
    const dir = scratch()
    writeGenerated(dir, GENERATED_FILES.panel, 'http: {}\n')
    writeGenerated(dir, GENERATED_FILES.shares, 'http: {}\n')
    expect(existsSync(join(dir, GENERATED_FILES.panel))).toBe(true)
    expect(existsSync(join(dir, GENERATED_FILES.shares))).toBe(true)
  })

  it('refuses every other file in the directory', () => {
    const dir = scratch()
    // These are the user's, and Traefik reads them.
    for (const name of ['middlewares.yaml', 'tcp.yaml', 'local-tls.yaml', 'auth.yaml']) {
      expect(() => writeGenerated(dir, name, 'http: {}\n')).toThrow(DynamicWriteRefused)
    }
  })

  it('refuses a path that tries to leave the directory', () => {
    const dir = scratch()
    for (const name of ['../compose.yaml', '../../.env', '/etc/passwd', 'sub/portta-panel.yaml']) {
      expect(() => writeGenerated(dir, name, 'x')).toThrow(DynamicWriteRefused)
    }
  })

  it('refuses to delete a file it does not own', () => {
    const dir = scratch()
    writeFileSync(join(dir, 'middlewares.yaml'), 'http: {}\n')
    expect(() => removeGenerated(dir, 'middlewares.yaml')).toThrow(DynamicWriteRefused)
    expect(existsSync(join(dir, 'middlewares.yaml'))).toBe(true)
  })

  it('writes 600, because these files carry a password hash', () => {
    const dir = scratch()
    writeGenerated(dir, GENERATED_FILES.panel, 'http: {}\n')
    expect(statSync(join(dir, GENERATED_FILES.panel)).mode & 0o777).toBe(0o600)
  })

  it('leaves no temporary file behind for Traefik to read', () => {
    const dir = scratch()
    writeGenerated(dir, GENERATED_FILES.panel, 'http: {}\n')
    expect(readdirSync(dir)).toEqual([GENERATED_FILES.panel])
  })
})

describe('renderPanelAuth', () => {
  it('declares the middleware the router names', () => {
    const yaml = renderPanelAuth({ user: 'dev', hash: '$apr1$abcdefgh$ckT15POyCRlen.h6XtGAZ1' })
    expect(yaml).toContain(`    ${PANEL_AUTH_MIDDLEWARE}:`)
    expect(yaml).toContain('- "dev:$apr1$abcdefgh$ckT15POyCRlen.h6XtGAZ1"')
    expect(yaml).toContain('removeHeader: true')
  })

  it('declares nothing when authentication is off, so the router fails closed', () => {
    const yaml = renderPanelAuth(null)
    expect(yaml).not.toContain(PANEL_AUTH_MIDDLEWARE)
  })

  it('writes comments and no `http` key at all when there is nothing to declare', () => {
    // `http: {}` is not an empty configuration to Traefik, it is an invalid
    // one, and one invalid file aborts every other file in the directory.
    const yaml = renderPanelAuth(null)
    expect(yaml).not.toMatch(/^http:/m)
    expect(yaml.split('\n').filter((line) => line !== '').every((line) => line.startsWith('#'))).toBe(true)
  })

  it('says who generated it, in both states', () => {
    for (const yaml of [renderPanelAuth(null), renderPanelAuth({ user: 'a', hash: 'b' })]) {
      expect(yaml).toContain('Generated by Portta panel')
      expect(yaml.endsWith('\n')).toBe(true)
    }
  })

  it('refuses a value that would break out of the YAML string', () => {
    expect(() => renderPanelAuth({ user: 'dev"', hash: 'x' })).toThrow(DynamicWriteRefused)
    expect(() => renderPanelAuth({ user: 'dev', hash: 'a\nrule: bad' })).toThrow(DynamicWriteRefused)
  })
})

describe('reconcilePanelAuth', () => {
  it('renders the file when a credential is configured', () => {
    const dir = scratch()
    const result = reconcilePanelAuth(dir, { mode: 'basic', user: 'dev', hash: '$apr1$a$b' })
    expect(result.written).toBe(true)
    expect(readFileSync(join(dir, GENERATED_FILES.panel), 'utf8')).toContain('dev:$apr1$a$b')
  })

  it('does not rewrite a file that is already in step', () => {
    const dir = scratch()
    const auth = { mode: 'basic', user: 'dev', hash: '$apr1$a$b' }
    reconcilePanelAuth(dir, auth)
    expect(reconcilePanelAuth(dir, auth)).toMatchObject({ written: false, reason: 'already in step' })
  })

  it('clears the middleware when the mode goes back to none', () => {
    const dir = scratch()
    reconcilePanelAuth(dir, { mode: 'basic', user: 'dev', hash: '$apr1$a$b' })
    reconcilePanelAuth(dir, { mode: 'none', user: '', hash: '' })
    expect(readFileSync(join(dir, GENERATED_FILES.panel), 'utf8')).not.toContain('basicAuth')
  })

  it('treats basic without a credential as no middleware at all', () => {
    const dir = scratch()
    reconcilePanelAuth(dir, { mode: 'basic', user: 'dev', hash: '' })
    expect(readFileSync(join(dir, GENERATED_FILES.panel), 'utf8')).not.toMatch(/^http:/m)
  })

  it('reports rather than throws when the directory cannot be written', () => {
    // The parent is a regular file, so this can never be created — ENOTDIR for
    // every user, root included. A procfs path looks equivalent and is not: on
    // Linux a recursive mkdir there never returns. Same fix as
    // overrides.test.ts.
    const unwritable = join(scratch(), 'not-a-directory')
    writeFileSync(unwritable, '')
    const result = reconcilePanelAuth(join(unwritable, 'nowhere'), {
      mode: 'basic',
      user: 'dev',
      hash: '$apr1$a$b',
    })
    expect(result.written).toBe(false)
  })
})
