#!/usr/bin/env bash
# `dev-gateway share`: the temporary hostnames the panel hands out.
#
# The panel creates shares, because that is where somebody decides to show a
# colleague a branch. The CLI manages them, so the two tools manage the same
# objects the way they already do for access bridges: `share list`, `revoke`
# and `gc` operate on exactly the file the panel wrote.
#
# The whole state is one generated file. Its metadata lives in a single comment
# line the Traefik file provider ignores, and the YAML below it is rendered
# from that line. tests/unit/share.test.sh asserts this renderer and the
# panel's produce the same bytes.
#
# See docs/sharing.md and docs/adr/0011-panel-reads-traefik-writes-one-file.md.

DG_SHARE_MARKER="# dev-gateway-shares: "

dg_share_file() { printf '%s/config/traefik/dynamic/dev-gateway-shares.yaml' "$DG_ROOT"; }

dg_cmd_share() {
  local sub="${1:-list}"; [ $# -gt 0 ] && shift || true
  case "$sub" in
    list|ls) dg_share_list "$@" ;;
    revoke|close|rm) dg_share_revoke "$@" ;;
    gc) dg_share_gc "$@" ;;
    -h|--help|help)
      cat >&2 <<'DG_HELP'
dev-gateway share: temporary hostnames for one service

  share list [--json]    Every share, its mode, and when it expires
  share revoke <id>      Remove one. The project itself is not touched
  share gc               Remove the ones that have expired

Shares are created from the panel, which is where somebody decides to show a
colleague a branch. They are an ADDITIONAL hostname pointing at a container:
the project's own router, labels and configuration are never changed, so
revoking one deletes a block from a generated file and nothing else.

Every share carries an expiry. `private` is the absence of a share, not a deny
rule, and a shared password is stored only as a hash.

See docs/sharing.md.
DG_HELP
      ;;
    *) err "unknown share subcommand: $sub"; hint "dev-gateway share --help"; return 1 ;;
  esac
}

# dg_share_meta: the JSON array of shares, or `[]`.
dg_share_meta() {
  local file line
  file=$(dg_share_file)
  [ -f "$file" ] || { printf '[]'; return 0; }
  line=$(grep -m1 "^$DG_SHARE_MARKER" "$file" 2>/dev/null) || { printf '[]'; return 0; }
  line=${line#"$DG_SHARE_MARKER"}
  [ -n "$line" ] || { printf '[]'; return 0; }
  printf '%s' "$line"
}

# dg_share_render: read the metadata array on stdin, write the whole file.
#
# One jq program rather than a shell loop, because it has to match
# renderShares() in web/src/server/core/shares.ts byte for byte, and a single
# expression is easier to keep in step than a dozen printfs.
dg_share_render() {
  dg_jq -r '
    # jq -r prints a trailing newline of its own, so the rendered lines stop at
    # the last content line: the file still ends with exactly one newline, the
    # same as renderShares() in the panel.
    def q: "\"" + . + "\"";
    def router: "dg-share-" + .id;
    . as $shares |
    [
      "# ============================================================================",
      "# Generated by the Dev Gateway panel. Edits are overwritten.",
      "# ============================================================================",
      "# Temporary shares: one additional hostname per service, each with an expiry.",
      "# A project'"'"'s own router is never touched, and revoking a share deletes a",
      "# block from this file. See docs/sharing.md.",
      "# ============================================================================",
      "# dev-gateway-shares: " + ($shares | tojson),
      ""
    ]
    + (if ($shares | length) == 0 then
        [
          "# Nothing is shared. \"Private\" is the absence of a share, not a deny rule.",
          "http: {}"
        ]
      else
        ["http:", "  routers:"]
        + ([ $shares[] | (. as $s |
            [ "    " + ($s | router) + ":",
              "      rule: " + (("Host(`" + $s.host + "`)") | q),
              "      entryPoints: [" + $s.entryPoint + "]" ]
            + (if $s.mode == "protected" then [ "      middlewares: [" + ($s | router) + "-auth]" ] else [] end)
            + [ "      service: " + ($s | router) ]
          ) ] | add)
        + ["  services:"]
        + ([ $shares[] | (. as $s |
            [ "    " + ($s | router) + ":",
              "      loadBalancer:",
              "        servers:",
              "          - url: " + (("http://" + $s.container + ":" + ($s.port | tostring)) | q) ]
          ) ] | add)
        + (if ([ $shares[] | select(.mode == "protected") ] | length) == 0 then [] else
            ["  middlewares:"]
            + ([ $shares[] | select(.mode == "protected") | (. as $s |
                [ "    " + ($s | router) + "-auth:",
                  "      basicAuth:",
                  "        users:",
                  "          - " + (($s.user + ":" + $s.hash) | q),
                  "        removeHeader: true" ]
              ) ] | add)
          end)
      end)
    | join("\n")
  '
}

# dg_share_write: read the metadata array on stdin, replace the file atomically.
dg_share_write() {
  local file tmp
  file=$(dg_share_file)
  mkdir -p "$(dirname "$file")" || return 1
  tmp="$file.dg-tmp.$$"
  if ! dg_share_render > "$tmp"; then
    rm -f "$tmp"
    err "could not render the shares file"
    hint "jq is needed here; the toolbox provides it: dev-gateway toolbox build"
    return 1
  fi
  chmod 600 "$tmp"
  mv "$tmp" "$file"
}

dg_share_list() {
  local as_json=0
  while [ $# -gt 0 ]; do
    case "$1" in
      --json) as_json=1 ;;
      *) die "unknown argument: $1" ;;
    esac
    shift
  done

  local meta now
  meta=$(dg_share_meta)
  now=$(date +%s)

  if [ "$as_json" = "1" ]; then
    printf '%s\n' "$meta"
    return 0
  fi

  if [ "$meta" = "[]" ]; then
    warn "nothing is shared"
    hint "shares are created from the panel: dev-gateway web up"
    return 0
  fi

  printf '%s\n' "$(dg_bold 'Temporary shares')"
  printf '  %-8s %-12s %-44s %-10s %s\n' "ID" "MODE" "HOSTNAME" "TARGET" "EXPIRES"
  printf '%s' "$meta" | dg_jq -r --argjson now "$now" '
    .[] | [ .id, .mode, .host, .container,
            (if .expiresAt <= $now then "expired"
             else ((.expiresAt - $now) / 60 | floor | tostring) + "m" end) ]
    | @tsv' 2>/dev/null | while IFS=$'\t' read -r id mode host target expires; do
    printf '  %-8s %-12s %-44s %-10s %s\n' "$id" "$mode" "$host" "$target" "$expires"
  done
  printf '\n'
  hint "dev-gateway share revoke <id>   removes one"
  hint "dev-gateway share gc            removes the expired ones"
}

dg_share_revoke() {
  local id="${1:-}"
  [ -n "$id" ] || { err "which share?"; hint "dev-gateway share list"; return 1; }
  case "$id" in
    *[!A-Za-z0-9]*) die "invalid share id: $id" ;;
  esac

  local meta kept
  meta=$(dg_share_meta)

  # Asked by id rather than by comparing the rendered arrays: the panel writes
  # compact JSON and jq re-emits it, and "did anything change" is the wrong
  # question when the answer could turn on a space.
  if ! printf '%s' "$meta" | dg_jq -e --arg id "$id" 'any(.[]; .id == $id)' >/dev/null 2>&1; then
    warn "no share '$id'"
    hint "dev-gateway share list"
    return 1
  fi

  kept=$(printf '%s' "$meta" | dg_jq -c --arg id "$id" '[ .[] | select(.id != $id) ]' 2>/dev/null)
  [ -n "$kept" ] || die "could not read the shares file"

  printf '%s' "$kept" | dg_share_write || return 1
  ok "share '$id' revoked; the project's own router was not touched"
  hint "Traefik hot-reloads the directory, so the hostname stops answering now"
}

dg_share_gc() {
  local meta kept now removed
  meta=$(dg_share_meta)
  now=$(date +%s)
  kept=$(printf '%s' "$meta" | dg_jq -c --argjson now "$now" '[ .[] | select(.expiresAt > $now) ]' 2>/dev/null)
  [ -n "$kept" ] || die "could not read the shares file"

  removed=$(( $(printf '%s' "$meta" | dg_jq -r 'length' 2>/dev/null || printf 0) \
            - $(printf '%s' "$kept" | dg_jq -r 'length' 2>/dev/null || printf 0) ))

  if [ "$removed" -le 0 ]; then
    ok "nothing has expired"
    return 0
  fi

  printf '%s' "$kept" | dg_share_write || return 1
  ok "removed $removed expired share(s)"
}
