// The only two files the panel is allowed to write into Traefik's dynamic
// configuration directory.
//
// The directory is mounted read-write, which makes the panel able to configure
// Traefik. That capability is bounded by name rather than by intention: a write
// to any other path is refused here, before it happens, the way
// docker/allowlist.ts refuses a Docker call. Everything else in the directory
// (middlewares.yaml, tcp.yaml, local-tls.yaml, anything a user dropped in)
// belongs to the user and is never touched.
//
// See docs/adr/0011-panel-reads-traefik-writes-one-file.md.

import {
  accessSync,
  constants,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'

/** The whole write surface. Nothing is added here without an ADR. */
export const GENERATED_FILES = {
  panel: 'dev-gateway-panel.yaml',
  shares: 'dev-gateway-shares.yaml',
} as const

export type GeneratedFile = (typeof GENERATED_FILES)[keyof typeof GENERATED_FILES]

const ALLOWED: readonly string[] = Object.values(GENERATED_FILES)

/** The middleware the panel's own router points at. */
export const PANEL_AUTH_MIDDLEWARE = 'dev-gateway-web-auth'

const HEADER = [
  '# ============================================================================',
  '# Generated by the Dev Gateway panel. Edits are overwritten.',
  '# ============================================================================',
  '# The panel writes this file and one other in this directory, and nothing',
  '# else here. See docs/adr/0011-panel-reads-traefik-writes-one-file.md.',
  '# ============================================================================',
  '',
]

export class DynamicWriteRefused extends Error {
  status = 403
  hint: string
  constructor(message: string, hint = 'this is a panel limit, not a filesystem one') {
    super(message)
    this.name = 'DynamicWriteRefused'
    this.hint = hint
  }
}

export function assertGenerated(name: string): asserts name is GeneratedFile {
  if (!ALLOWED.includes(name)) {
    throw new DynamicWriteRefused(
      `the panel only writes ${ALLOWED.join(' and ')} in Traefik's dynamic directory`,
    )
  }
}

/** YAML double-quoted scalar. Refuses anything that would need escaping. */
export function quote(value: string): string {
  if (/["\\\n\r]/.test(value)) {
    throw new DynamicWriteRefused(`refusing to write a value containing quotes or newlines: ${value}`)
  }
  return `"${value}"`
}

export function renderPanelAuth(options: { user: string; hash: string } | null): string {
  if (!options) {
    // Comments and nothing else. `http: {}` is not an empty configuration to
    // Traefik, it is an invalid one ("http cannot be a standalone element"),
    // and one invalid file aborts the whole directory: every other generated
    // router would stop being served too.
    return [
      ...HEADER,
      '# DEV_GATEWAY_WEB_AUTH is not `basic`, so the panel declares no middleware.',
      '# A router that references one will be rejected by Traefik, which is the',
      '# correct direction to fail.',
    ].join('\n') + '\n'
  }

  return [
    ...HEADER,
    '# BasicAuth in front of the panel\'s own router. There is no session, no',
    '# cookie and no login form: the request either reaches the container or it',
    '# does not. See docs/adr/0012-panel-authentication-is-traefiks.md.',
    'http:',
    '  middlewares:',
    `    ${PANEL_AUTH_MIDDLEWARE}:`,
    '      basicAuth:',
    '        users:',
    `          - ${quote(`${options.user}:${options.hash}`)}`,
    '        realm: "Dev Gateway"',
    '        removeHeader: true',
    '',
  ].join('\n')
}

export function dynamicPath(dir: string, name: string): string {
  assertGenerated(name)
  return join(dir, name)
}

export function isDirWritable(dir: string): boolean {
  try {
    accessSync(dir, constants.W_OK)
    return true
  } catch {
    return false
  }
}

export function readGenerated(dir: string, name: string): string | null {
  const path = dynamicPath(dir, name)
  if (!existsSync(path)) return null
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return null
  }
}

/**
 * Writes through a temporary file in the same directory, so Traefik's watcher
 * never sees a half-written router. Mode 600: these files carry password
 * hashes, and Traefik reads them as root.
 */
export function writeGenerated(dir: string, name: string, contents: string): void {
  const path = dynamicPath(dir, name)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true, mode: 0o700 })

  const temporary = join(dir, `.dg-${name}.${process.pid}.tmp`)
  try {
    writeFileSync(temporary, contents, { mode: 0o600 })
    renameSync(temporary, path)
  } catch (cause) {
    try {
      if (existsSync(temporary)) unlinkSync(temporary)
    } catch {
      /* nothing else to do */
    }
    throw cause
  }
}

export function removeGenerated(dir: string, name: string): void {
  const path = dynamicPath(dir, name)
  if (!existsSync(path)) return
  unlinkSync(path)
}

/**
 * Brings `dev-gateway-panel.yaml` in line with the settings the panel was
 * started with. Returns what happened, because a panel that could not write is
 * a diagnostic rather than a crash: on Linux the directory may well belong to
 * another user, and `dev-gateway web auth set` writes the same file from the
 * host.
 */
export function reconcilePanelAuth(
  dir: string,
  auth: { mode: string; user: string; hash: string },
): { written: boolean; reason: string } {
  const wanted = renderPanelAuth(
    auth.mode === 'basic' && auth.user !== '' && auth.hash !== ''
      ? { user: auth.user, hash: auth.hash }
      : null,
  )

  const current = readGenerated(dir, GENERATED_FILES.panel)
  if (current === wanted) return { written: false, reason: 'already in step' }
  if (!isDirWritable(dir)) return { written: false, reason: 'the dynamic directory is not writable' }

  try {
    writeGenerated(dir, GENERATED_FILES.panel, wanted)
    return { written: true, reason: 'rendered from the current settings' }
  } catch (cause) {
    return { written: false, reason: String(cause) }
  }
}
