#!/usr/bin/env bash
# ============================================================================
# Temporary shares: the file, and what may never be in it
# ============================================================================
# The panel creates shares and the CLI manages them, so both render the same
# file. A drift between the two renderers would silently drop somebody's
# routers on the next `share gc`, which is why the bytes are compared here
# rather than the behaviour described somewhere.
# ============================================================================
set -uo pipefail

DG_TEST_DIR=$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
. "$DG_TEST_DIR/lib/assert.sh"
DG_ROOT=$(cd -P "$DG_TEST_DIR/.." && pwd); export DG_ROOT
cd "$DG_ROOT" || exit 1
. "$DG_ROOT/scripts/lib/common.sh"
. "$DG_ROOT/scripts/lib/docker.sh"
. "$DG_ROOT/scripts/lib/toolbox.sh"
. "$DG_ROOT/scripts/cmd/share.sh"

WORK=$(mktemp -d -t dg-share-test) || exit 1
trap 'rm -rf "$WORK"' EXIT INT TERM

FIXTURE='[{"id":"a7f3","project":"storefront","service":"web","container":"storefront-web-1","port":3000,"host":"storefront-web-a7f3.share.dev.example.com","mode":"protected","user":"reviewer","hash":"$apr1$abcdefgh$ckT15POyCRlen.h6XtGAZ1","entryPoint":"websecure","createdAt":1700000000,"expiresAt":1700021600},{"id":"b104","project":"checkout","service":"api","container":"checkout-api-1","port":8000,"host":"checkout-api-b104.share.dev.example.com","mode":"public","user":null,"hash":null,"entryPoint":"web","createdAt":1700000000,"expiresAt":1700007200}]'

describe "the CLI and the panel render the same file, byte for byte"

if ! command -v node >/dev/null 2>&1; then
  it "needs node to compare the two renderers"; skip "node not installed"
elif ! dg_have jq; then
  it "needs jq on the host"; skip "jq not installed"
else
  printf '%s' "$FIXTURE" > "$WORK/shares.json"

  render_cli() { printf '%s' "$1" | dg_share_render; }
  render_panel() {
    printf '%s' "$1" > "$WORK/in.json"
    ( cd "$DG_ROOT/web" && node --experimental-strip-types -e "
        const fs = require('node:fs')
        import('./src/server/core/shares.ts').then((m) =>
          process.stdout.write(m.renderShares(JSON.parse(fs.readFileSync(process.argv[1], 'utf8')))))
      " "$WORK/in.json" ) 2>/dev/null
  }

  it "two shares, one protected and one public"
  assert_eq "$(render_panel "$FIXTURE")" "$(render_cli "$FIXTURE")"

  it "no shares at all"
  assert_eq "$(render_panel '[]')" "$(render_cli '[]')"

  it "and the empty file still says private is the absence of a share"
  assert_contains "$(render_cli '[]')" "not a deny rule"
fi

describe "what a rendered share does, and does not, contain"

if ! dg_have jq; then
  it "needs jq on the host"; skip "jq not installed"
else
  rendered=$(printf '%s' "$FIXTURE" | dg_share_render)

  it "the router points at the container name, never the compose alias"
  assert_contains "$rendered" 'url: "http://storefront-web-1:3000"'

  it "a protected share carries a hash"
  assert_contains "$rendered" '$apr1$'

  it "and never a password"
  assert_not_contains "$rendered" "password"

  it "a public share gets no middleware"
  assert_not_contains "$rendered" "dg-share-b104-auth"

  it "TLS decides the entrypoint, per share"
  assert_contains "$rendered" "entryPoints: [websecure]"
  it "and a share made without TLS says so"
  assert_contains "$rendered" "entryPoints: [web]"

  it "shared hostnames are visibly not project hostnames"
  assert_contains "$rendered" ".share.dev.example.com"

  it "the file says what wrote it"
  assert_contains "$rendered" "Generated by the Dev Gateway panel"

  it "and carries its own state, in a comment Traefik ignores"
  assert_contains "$rendered" "# dev-gateway-shares: "

  it "no project's own router appears anywhere in it"
  assert_eq "" "$(printf '%s' "$rendered" | grep -n 'traefik\.http\.routers' || true)"
fi

describe "revoke and gc operate on that file and nothing else"

if ! dg_have jq; then
  it "needs jq on the host"; skip "jq not installed"
else
  # A scratch DG_ROOT, so the repository's own dynamic directory is untouched.
  SCRATCH="$WORK/root"
  mkdir -p "$SCRATCH/config/traefik/dynamic"
  ( DG_ROOT="$SCRATCH" printf '%s' "$FIXTURE" | DG_ROOT="$SCRATCH" dg_share_write ) >/dev/null 2>&1

  scratch() { DG_ROOT="$SCRATCH" "$@"; }

  it "the file was written where the panel mounts it"
  assert_success test -f "$SCRATCH/config/traefik/dynamic/dev-gateway-shares.yaml"

  it "and only that file exists in the directory"
  assert_eq "dev-gateway-shares.yaml" "$(ls "$SCRATCH/config/traefik/dynamic")"

  it "it is 600, because it carries a password hash"
  assert_eq "600" "$(stat -f '%Lp' "$SCRATCH/config/traefik/dynamic/dev-gateway-shares.yaml" 2>/dev/null \
    || stat -c '%a' "$SCRATCH/config/traefik/dynamic/dev-gateway-shares.yaml" 2>/dev/null)"

  it "list reads back what was written"
  assert_contains "$(scratch dg_share_list 2>&1)" "a7f3"

  it "revoking one leaves the other"
  scratch dg_share_revoke a7f3 >/dev/null 2>&1
  assert_not_contains "$(cat "$SCRATCH/config/traefik/dynamic/dev-gateway-shares.yaml")" "a7f3"

  it "and the other is still routed"
  assert_contains "$(cat "$SCRATCH/config/traefik/dynamic/dev-gateway-shares.yaml")" "dg-share-b104"

  it "revoking one that does not exist fails rather than rewriting the file"
  assert_failure scratch dg_share_revoke deadbeef

  it "an id that is not an id is refused"
  assert_failure scratch dg_share_revoke '../../etc/passwd'

  it "gc removes what has expired"
  scratch dg_share_gc >/dev/null 2>&1
  assert_eq "[]" "$(scratch dg_share_meta)"

  it "and leaves a file with no http key at all, which Traefik accepts"
  # `http: {}` is invalid to Traefik, and one invalid file in the directory
  # aborts every other file in it, including the panel's own middleware.
  assert_eq "" "$(grep -n '^http:' "$SCRATCH/config/traefik/dynamic/dev-gateway-shares.yaml" || true)"
  it "while still saying what it is"
  assert_contains "$(cat "$SCRATCH/config/traefik/dynamic/dev-gateway-shares.yaml")" "not a deny rule"
fi

describe "the command surface"

it "share answers --help"
assert_contains "$(./bin/dev-gateway share --help 2>&1)" "dev-gateway share"

it "an unknown subcommand fails"
assert_failure ./bin/dev-gateway share definitely-not-a-subcommand

it "revoke without an id fails"
assert_failure ./bin/dev-gateway share revoke

it "the CLI never creates a share: that decision is made in the panel"
assert_eq "" "$(grep -n 'dg_share_create' scripts/cmd/share.sh || true)"

it "the generated file is git-ignored, because it carries a hash"
assert_contains "$(cat .gitignore)" "config/traefik/dynamic/dev-gateway-shares.yaml"

describe "the panel refuses what should never be shared"

shares="web/src/server/core/shares.ts"

it "a non-HTTP service"
assert_contains "$(cat "$shares")" "is not an HTTP service"

it "a service off the shared network"
assert_contains "$(cat "$shares")" "is not on the"

it "public without PUBLIC_ENABLED"
assert_contains "$(cat "$shares")" "PUBLIC_ENABLED=true"

it "a password over plaintext on a remote profile"
assert_contains "$(cat "$shares")" "not protection"

it "and an expiry is mandatory, not a default somebody can remove"
assert_contains "$(cat "$shares")" "an exposure nobody remembers to close"

t_summary
