import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync } from 'node:fs'
import { resolve, relative } from 'node:path'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { compileDocumentation, validateDocumentation } from '../packages/core/src/documentation-compile.ts'

export const repositoryRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
export function collectKnowledge(root = repositoryRoot, validate = false) {
  const manifest = JSON.parse(readFileSync(resolve(root, 'docs/navigation.json'), 'utf8'))
  const sources = {}
  const walk = (directory) => {
    for (const name of readdirSync(resolve(root, directory)).sort()) {
      const path = `${directory}/${name}`
      if (statSync(resolve(root, path)).isDirectory()) walk(path)
      else if (path.endsWith('.md')) sources[path] = readFileSync(resolve(root, path), 'utf8')
    }
  }
  walk('docs/product'); walk('docs/development')
  sources['CHANGELOG.md'] = readFileSync(resolve(root, 'CHANGELOG.md'), 'utf8')
  const version = JSON.parse(readFileSync(resolve(root, 'packages/cli/package.json'), 'utf8')).version
  let revision = process.env.PORTTA_REVISION || null
  if (!revision) { try { revision = execFileSync('git', ['status', '--porcelain', '--', 'docs/product', 'docs/development', 'docs/navigation.json', 'CHANGELOG.md'], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim() ? null : execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim() } catch {} }
  const hash = createHash('sha256').update(JSON.stringify({ manifest, sources: Object.fromEntries(Object.entries(sources).sort(([a], [b]) => a < b ? -1 : 1)) })).digest('hex')
  const corpus = compileDocumentation(manifest, sources, { version, revision, hash })
  const assets = readdirSync(resolve(root, 'docs/images')).map((file) => `docs/images/${file}`)
  validateDocumentation(corpus, [...Object.keys(sources), ...assets], {}, false)
  if (validate) {
    const tracked = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard'], { cwd: root, encoding: 'utf8' }).trim().split('\n')
      .filter((path) => existsSync(resolve(root, path)))
    const files = [...new Set([...tracked, ...Object.keys(sources)])]
    const extras = {}
    for (const path of ['README.md', 'AGENTS.md', 'CLAUDE.md', 'docs/agent-guidelines.md']) if (existsSync(resolve(root, path))) extras[path] = readFileSync(resolve(root, path), 'utf8')
    validateDocumentation(corpus, files, extras)
    // Product messages use the generated source map. Validate their anchors too.
    for (const path of files.filter((path) => /^(apps|packages)\/.+\.(ts|tsx|json)$/.test(path) && !/(?:test|generated|openapi|package-lock)/.test(path))) {
      const text = readFileSync(resolve(root, path), 'utf8')
      for (const citation of text.matchAll(/docs\/(?:product|development)\/[\w./-]+\.md(?:#[\w-]+)?/g)) {
        const [source, anchor] = citation[0].split('#')
        const page = corpus.pages.find((page) => page.source === source)
        if (!page || (anchor && !page.headings.some((heading) => heading.id === anchor))) throw new Error(`${path}: invalid citation ${citation[0]}`)
      }
    }
  }
  return corpus
}
export function githubIndex(corpus) {
  let text = '# Documentation\n\nCanonical documentation for this checkout and the installed Portta version.\nUse `/docs` in the panel, `portta docs` in a terminal, or the documentation MCP tools.\n\n<!-- Generated by npm run docs:generate. Edit navigation.json and the source pages. -->\n'
  let audience = ''
  for (const group of corpus.groups) {
    if (audience !== group.audience) { audience = group.audience; text += `\n## ${audience === 'user' ? 'User and operator' : 'Developer and contributor'}\n` }
    text += `\n### ${group.title}${group.category ? ` / ${group.category}` : ''}\n\n`
    for (const slug of group.slugs) {
      const page = corpus.pages.find((page) => page.slug === slug)
      const target = page.kind === 'api' ? '../packages/contracts/openapi.json' : relative('docs', page.source)
      text += `- [${page.title}](${target}) — ${page.description}\n`
    }
  }
  return text+'\n## Repository-only instructions\n\n[Shared-host operating rules](agent-guidelines.md) govern agents. Research and internal instructions are not part of the published corpus.\n'
}
export function citationMap(corpus) {
  return '// Generated by npm run docs:generate. Do not edit.\nexport const DOC_PATHS: Record<string, string> = '+JSON.stringify(Object.fromEntries(corpus.pages.filter((page) => page.kind === 'markdown').map((page) => [page.source,page.slug])),null,2)+'\n'
}
export function writeCorpus(corpus, path) { mkdirSync(resolve(path, '..'), { recursive: true }); writeFileSync(path, JSON.stringify(corpus)+'\n') }

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check')
  const bundleOnly = process.argv.includes('--bundle')
  const corpus = collectKnowledge(repositoryRoot, !bundleOnly)
  if (!bundleOnly) for (const [path, content] of [['docs/README.md',githubIndex(corpus)], ['packages/contracts/src/docs-paths.generated.ts',citationMap(corpus)]]) {
    if (check) { if (readFileSync(resolve(repositoryRoot,path),'utf8') !== content) throw new Error(`${path} is stale; run npm run docs:generate`) }
    else writeFileSync(resolve(repositoryRoot,path),content)
  }
  if (!check) writeCorpus(corpus,resolve(repositoryRoot,'docs/.generated/corpus.json'))
  console.log(`Documentation: ${corpus.pages.length} classified pages, ${corpus.identity.hash.slice(0,12)}${check ? ' validated' : ' generated'}`)
}
